environment:

  matrix:
    # Test on same python versions as Travis (32-bit and 64-bit)
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python36-x64"

build: off

install:
  # Get python version
  - "%PYTHON%\\python.exe --version"
  # Install test dependencies
  - "%PYTHON%\\python.exe -m pip install -r test_requirements.txt"

test_script:
  # Run test script
  - "%PYTHON%/Scripts/py.test"
